export default {
  NAME: 'Name',
  CONTACT: 'Contact',
  ADDRESS: 'Address',
  SUBMIT: 'Submit',
  UPDATE: 'Update',
  DELETE: 'Delete',
  TITLE_DELETE_USER: 'Confirm Delete',
  SUB_TITLE_DELETE_USER: 'Are you sure you want to delete this user ?',
  SUCCESS: 'Success',
  FAILED: 'Failed',
  REGISTERED_SUCCESS: 'You are registered successfully',
  PLEASE_ADDRESS: 'Please fill Address',
  PLEASE_NAME: 'Please fill Name',
  PLEASE_CONTACT: 'Please fill Contact Number',
  NOT_FOUND: 'No found',
};
